#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Write docs/WORKED_EXAMPLE.md: one input record from each vendor (taken from
the synthetic fixtures) and the exact canonical rows the loaders produce.

    python3 docs/make_worked_example.py
"""

import re
import sqlite3
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "tests" / "data"

COLS = ("panel_name", "report_id", "genome_build", "gene", "variant_type", "chrom", "pos", "ref", "alt",
        "cds_effect", "protein_effect", "hgvs_c", "hgvs_p", "functional_effect", "functional_effect_so",
        "functional_effect_source", "status", "origin", "allele_fraction", "depth")


def load(db):
    meta = DATA / "case_metadata.csv"
    for loader, sub in (("load_foundation.py", "foundation"), ("load_genminetop.py", "genminetop"),
                        ("load_guardant.py", "guardant")):
        subprocess.run([sys.executable, str(ROOT / loader), str(db), str(DATA / sub), "--case-metadata", str(meta),
                        "--quiet"], check=True, capture_output=True)


def row_table(conn, where, args):
    sql = (f"SELECT {', '.join('c.' + c if c in ('panel_name', 'report_id', 'genome_build') else 'v.' + c for c in COLS)} "
           f"FROM variants v JOIN cases c USING(case_id) WHERE {where}")
    r = conn.execute(sql, args).fetchone()
    lines = ["| column | value |", "|---|---|"]
    for k, v in zip(COLS, r):
        v = "NULL" if v is None else (f"{v:.4f}" if isinstance(v, float) else str(v))
        lines.append(f"| {k} | `{v}` |")
    return "\n".join(lines)


def main():
    fm = (DATA / "foundation" / "SYN-F1-0001.xml").read_text(encoding="utf-8")
    fm_rec = re.search(r"\s*<short-variant [^>]*gene=\"KRAS\".*?</short-variant>", fm, re.S).group(0)
    fm_splice = re.search(r"\s*<short-variant [^>]*gene=\"SMAD4\".*?</short-variant>", fm, re.S).group(0)
    gm = (DATA / "genminetop" / "SYN-GM-0001.xml").read_text(encoding="utf-8")
    items = re.findall(r"      <item>\n.*?\n      </item>", gm, re.S)
    gm_rec = next(i for i in items if "<gene>KRAS</gene>" in i)
    gm_splice = next(i for i in items if "<gene>SMAD4</gene>" in i)

    with tempfile.TemporaryDirectory() as tmp:
        db = Path(tmp) / "panels.db"
        load(db)
        conn = sqlite3.connect(db)
        t_fm = row_table(conn, "c.report_id = ? AND v.gene = 'KRAS'", ("SYN-F1-0001",))
        t_gm = row_table(conn, "c.report_id = ? AND v.gene = 'KRAS'", ("SYN-GM-0001",))
        t_gd = row_table(conn, "c.report_id = ? AND v.gene = 'KRAS'", ("SYN-G360-0001",))
        t_fs = row_table(conn, "c.report_id = ? AND v.gene = 'SMAD4'", ("SYN-F1-0001",))
        t_gs = row_table(conn, "c.report_id = ? AND v.gene = 'SMAD4'", ("SYN-GM-0001",))
        t_gi = row_table(conn, "c.report_id = ? AND v.gene = 'APC' AND v.hgvs_p IS NULL", ("SYN-G360-0001",))
        bm = conn.execute("SELECT c.report_id, b.name, b.value, b.unit, b.call, b.call_raw, b.assay "
                          "FROM biomarkers b JOIN cases c USING(case_id) ORDER BY c.case_id, b.name").fetchall()

    bm_table = ["| report_id | name | value | unit | call | call_raw | assay |", "|---|---|---|---|---|---|---|"]
    for r in bm:
        bm_table.append("| " + " | ".join("" if x is None else str(x) for x in r) + " |")

    md = f"""# Worked example: from vendor records to canonical rows

Generated by `docs/make_worked_example.py` from the synthetic fixtures in
`tests/data/`; the tables below are the literal output of the loaders.

The same alteration — KRAS c.35G>A p.G12D — is reported by three vendors in
three formats, on two genome builds, with and without the `p.` prefix.  After
loading, the three rows share `hgvs_p = p.G12D` and the Sequence Ontology term
`missense_variant`, while the vendor strings and native coordinates are kept.

## 1. Foundation Medicine XML (`SYN-F1-0001.xml`)

```xml{fm_rec}
```

{t_fm}

## 2. GenMineTOP XML (`SYN-GM-0001.xml`)

```xml
{gm_rec}
```

{t_gm}

## 3. Guardant360 CDx workbook (`Interim_SYN-G360-0001_SYNPT-0001.xlsx`, sheet `SNV`)

| gene | chrom | position | mut_nt | mut_aa | cdna | percentage | call | transcript_id | exon | reporting_category |
|---|---|---|---|---|---|---|---|---|---|---|
| KRAS | 12 | 25398284 | C>T | G12D | c.35G>A | 4.21 | 1 | NM_004985.5 | 2.0 | protein_coding |

{t_gd}

## 4. Splice variants without a protein change

Foundation Medicine reports a splice-site change with a vendor category:

```xml{fm_splice}
```

{t_fs}

GenMineTOP reports a deletion that removes the acceptor site but gives no
protein change; the consequence is inferred from the coding change
(`c.905-9_905del` spans intron positions −9…−1 and the first exonic base):

```xml
{gm_splice}
```

{t_gs}

Guardant reports a coding deletion without `mut_aa`; the consequence is
inferred from the length of the deleted coding sequence:

{t_gi}

## 5. Biomarkers

TMB and MSI are stored with unit and assay; the Guardant MSI score is an MSI
record, never a TMB value.

{chr(10).join(bm_table)}
"""
    out = ROOT / "docs" / "WORKED_EXAMPLE.md"
    out.write_text(md, encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
